import { Franchise, Exhibition, Investor } from './types';

export const mockFranchises: Franchise[] = [
  {
    id: '1',
    name: 'QuickByte Cafe',
    category: 'Food & Beverage',
    investmentRange: { min: 250000, max: 500000 },
    description:
      'A modern cafe concept offering premium coffee, specialty beverages, and quick-service meals. Known for sustainable practices and innovative menu development.',
    shortDescription: 'Premium specialty cafe with sustainable practices',
    roi: 18,
    yearsInBusiness: 8,
    unitsOperating: 156,
    supportLevel: 'Comprehensive',
    image: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=800&q=80',
    highlights: [
      'Proven business model',
      'Comprehensive training program',
      'Supply chain support',
      'Marketing & branding package',
    ],
  },
  {
    id: '2',
    name: 'FitZone Pro',
    category: 'Fitness & Wellness',
    investmentRange: { min: 300000, max: 600000 },
    description:
      'State-of-the-art fitness center combining modern equipment with personal training and group classes. Technology-driven member experience.',
    shortDescription: 'Tech-enabled fitness center with premium equipment',
    roi: 22,
    yearsInBusiness: 6,
    unitsOperating: 89,
    supportLevel: 'Premium',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    highlights: [
      'State-of-the-art equipment',
      'Digital member platform',
      'Certified trainers',
      'Revenue sharing model',
    ],
  },
  {
    id: '3',
    name: 'LearnHub Academy',
    category: 'Education',
    investmentRange: { min: 150000, max: 350000 },
    description:
      'Online and offline tutoring platform specializing in STEM subjects for K-12 students. Blended learning model with certified instructors.',
    shortDescription: 'STEM education with blended learning approach',
    roi: 16,
    yearsInBusiness: 5,
    unitsOperating: 124,
    supportLevel: 'Standard',
    image: 'https://images.unsplash.com/photo-1427504494785-cdea0d6af511?w=800&q=80',
    highlights: [
      'Curriculum provided',
      'Online platform',
      'Instructor certification',
      'Student management system',
    ],
  },
  {
    id: '4',
    name: 'StyleNest Salon',
    category: 'Beauty & Personal Care',
    investmentRange: { min: 200000, max: 400000 },
    description:
      'Premium hair and beauty salon offering cutting-edge treatments and services. Focus on customer experience and professional development.',
    shortDescription: 'Premium beauty salon with professional services',
    roi: 20,
    yearsInBusiness: 7,
    unitsOperating: 98,
    supportLevel: 'Premium',
    image: 'https://images.unsplash.com/photo-1560066169-b8a46d2331ad?w=800&q=80',
    highlights: [
      'Premium brand positioning',
      'Staff training program',
      'Product line included',
      'Salon design package',
    ],
  },
  {
    id: '5',
    name: 'RetailPro Store',
    category: 'Retail',
    investmentRange: { min: 350000, max: 750000 },
    description:
      'Contemporary retail concept featuring fashion, accessories, and lifestyle products. Integrated digital and physical shopping experience.',
    shortDescription: 'Modern retail with integrated digital experience',
    roi: 15,
    yearsInBusiness: 9,
    unitsOperating: 142,
    supportLevel: 'Comprehensive',
    image: 'https://images.unsplash.com/photo-1555696365-27c7500d50f6?w=800&q=80',
    highlights: [
      'Product sourcing network',
      'POS system provided',
      'Marketing support',
      'Inventory management tools',
    ],
  },
  {
    id: '6',
    name: 'TechHub Solutions',
    category: 'Technology Services',
    investmentRange: { min: 100000, max: 250000 },
    description:
      'IT solutions and consulting services for small to medium businesses. Focus on cloud migration and cybersecurity.',
    shortDescription: 'IT consulting and solutions provider',
    roi: 24,
    yearsInBusiness: 4,
    unitsOperating: 76,
    supportLevel: 'Standard',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    highlights: [
      'Technical certification',
      'Client management platform',
      'Service delivery framework',
      'Lead generation support',
    ],
  },
];

export const mockExhibitions: Exhibition[] = [
  {
    id: '1',
    name: 'International Franchise Expo 2026',
    date: new Date('2026-05-15'),
    location: 'Convention Center, New York',
    description:
      'The largest franchise exhibition featuring over 300 brands and attracting thousands of entrepreneurs and investors.',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
    featured: true,
    attendees: 5000,
    booths: 320,
  },
  {
    id: '2',
    name: 'Spring Business Opportunities Summit',
    date: new Date('2026-04-20'),
    location: 'Tech Plaza, Los Angeles',
    description:
      'Focused summit on modern franchise models with emphasis on technology-enabled brands and sustainability.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    featured: true,
    attendees: 2500,
    booths: 150,
  },
  {
    id: '3',
    name: 'Regional Franchise Forum - Southeast',
    date: new Date('2026-06-10'),
    location: 'Hilton Downtown, Atlanta',
    description:
      'Regional networking event connecting franchisors with potential franchisees in the Southeast territory.',
    image: 'https://images.unsplash.com/photo-1522194194294-ebd7d26ae3a7?w=800&q=80',
    featured: false,
    attendees: 800,
    booths: 60,
  },
];

export const mockInvestors: Investor[] = [
  {
    id: '1',
    name: 'Rajinder Kumar',
    location: 'Mumbai, India',
    investmentCapacity: '₹50L - ₹1Cr',
    preferredIndustries: ['Food & Beverage', 'Retail'],
    experience: 'Multi-unit Franchisee',
    description: 'Experienced entrepreneur looking to diversify into the quick-service restaurant space in Tier-1 cities.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    verified: true,
  },
  {
    id: '2',
    name: 'Anita Sharma',
    location: 'Delhi NCR, India',
    investmentCapacity: '₹20L - ₹50L',
    preferredIndustries: ['Education', 'Wellness'],
    experience: 'Former Educator',
    description: 'Passionate about educational technology and wellness programs for children. Seeking scalable models.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
    verified: true,
  },
  {
    id: '3',
    name: 'Vikram Singh',
    location: 'Bangalore, India',
    investmentCapacity: '₹1Cr+',
    preferredIndustries: ['Technology Services', 'Automotive'],
    experience: 'Serial Entrepreneur',
    description: 'Tech-focused investor looking for high-growth service models with strong digital infrastructure.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    verified: true,
  },
  {
    id: '4',
    name: 'Priya Iyer',
    location: 'Chennai, India',
    investmentCapacity: '₹10L - ₹20L',
    preferredIndustries: ['Beauty & Personal Care'],
    experience: 'Business Manager',
    description: 'Looking to start a boutique salon or spa. Interested in premium global brands entered the Indian market.',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    verified: false,
  },
];
